import { z } from "zod"

import * as service from "@/server/modules/finance/finance.service"
import { actorFromSession } from "@/server/modules/shared/actor"
import { advanceKindSchema, advanceStatusSchema, idSchema, localDateSchema, paginationInput, periodSchema, positiveMoneySchema } from "@/server/modules/shared/schemas"

import { createTRPCRouter, managerProcedure, staffProcedure } from "../init"

export const expenseSchema = z.object({
  id: idSchema,
  description: z.string(),
  category: z.string(),
  amount: z.number(),
  incurredOn: localDateSchema,
  createdAt: z.string(),
})

export const advanceSchema = z.object({
  id: idSchema,
  memberId: idSchema,
  memberName: z.string(),
  kind: advanceKindSchema,
  description: z.string(),
  amount: z.number(),
  grantedOn: localDateSchema,
  status: advanceStatusSchema,
  deductedInPayoutId: idSchema.nullable(),
  originAdvanceId: idSchema.nullable(),
  generatedByPayoutId: idSchema.nullable(),
  cancelReason: z.string().nullable(),
  createdAt: z.string(),
})

export const expensesRouter = createTRPCRouter({
  list: staffProcedure
    .input(z.object({ period: periodSchema, ...paginationInput }))
    .output(z.object({ items: z.array(expenseSchema), nextCursor: z.string().nullable(), total: z.number(), periodClosed: z.boolean(), closedPayoutId: idSchema.nullable() }))
    .query(({ ctx, input }) => service.listExpenses(ctx.db, actorFromSession(ctx.session), input)),

  create: staffProcedure
    .input(
      z.object({
        description: z.string().trim().min(2).max(200),
        category: z.string().trim().min(1).max(50).optional(),
        amount: positiveMoneySchema,
        incurredOn: localDateSchema,
      }),
    )
    .output(expenseSchema)
    .mutation(({ ctx, input }) => service.createExpense(ctx.db, actorFromSession(ctx.session), input)),

  delete: managerProcedure
    .input(z.object({ id: idSchema, reason: z.string().trim().max(500).optional() }))
    .output(z.object({ ok: z.literal(true) }))
    .mutation(({ ctx, input }) => service.deleteExpense(ctx.db, actorFromSession(ctx.session), input.id, input.reason)),
})

export const advancesRouter = createTRPCRouter({
  list: staffProcedure
    .input(z.object({ status: advanceStatusSchema.optional(), memberId: idSchema.optional(), period: periodSchema.optional(), ...paginationInput }))
    .output(z.object({ items: z.array(advanceSchema), nextCursor: z.string().nullable(), total: z.number(), periodClosed: z.boolean(), closedPayoutId: idSchema.nullable() }))
    .query(({ ctx, input }) => service.listAdvances(ctx.db, actorFromSession(ctx.session), input)),

  create: staffProcedure
    .input(
      z.object({
        memberId: idSchema,
        // carry_over is generated by the system only (API-advances-create).
        kind: z.enum(["cash_advance", "purchase", "other"]).default("cash_advance"),
        description: z.string().trim().min(1).max(200),
        amount: positiveMoneySchema,
        grantedOn: localDateSchema,
      }),
    )
    .output(advanceSchema)
    .mutation(({ ctx, input }) => service.createAdvance(ctx.db, actorFromSession(ctx.session), input)),

  cancel: managerProcedure
    .input(z.object({ id: idSchema, reason: z.string().trim().min(3).max(500) }))
    .output(advanceSchema)
    .mutation(({ ctx, input }) => service.cancelAdvance(ctx.db, actorFromSession(ctx.session), input.id, input.reason)),
})
